CREATE PROCEDURE [dbo].[PROC_OUTSTANDING]
(
@CMP_CODE NVARCHAR(50),
@DATABASENAME NVARCHAR(50),
@RPT_WISE INT,
@RPT_TYPE INT,
@TEMPTABLE NVARCHAR(20),
@ASONDATE  NVARCHAR(20),
@ONACCOUNT  INT,
@DUEPENDING  INT,
@DAYS NVARCHAR(4),
@PREVDATABASE NVARCHAR(20)

)
AS



DECLARE @SQL AS NVARCHAR(4000)
DECLARE @SQLJOIN AS NVARCHAR(4000)
DECLARE @SQLONACCOUNT AS NVARCHAR(4000)
DECLARE @SQLONACCOUNT1 AS NVARCHAR(4000)
DECLARE @SQLONACCOUNT2 AS NVARCHAR(4000)
DECLARE @SQLONACCOUNT3 AS NVARCHAR(4000)
DECLARE @SQLONACCOUNT4 AS NVARCHAR(4000)
DECLARE @SQLONACCOUNT5 AS NVARCHAR(4000)
DECLARE @SQLONACCOUNT6 AS NVARCHAR(4000)
DECLARE @SQLONACCOUNT7 AS NVARCHAR(4000)
DECLARE @CONDITION AS NVARCHAR(2000)
DECLARE @ALL AS NVARCHAR(50)
DECLARE @ORDERBYSQL AS NVARCHAR(1000)


SET @CONDITION=""
SET @SQLJOIN =""
SET @SQLONACCOUNT3=""
SET @ALL=""
SET @ORDERBYSQL=""

BEGIN
IF @RPT_WISE=1 
BEGIN    
SET @SQLJOIN=" INNER JOIN " + @TEMPTABLE + " TT ON LM.LGR_ID=TT.CODE"
SET @ORDERBYSQL=" ORDER BY CITY,PARTY_CITYID,PARTY,LGR_ID,FLAG,DATE,BILL_NO"
END

ELSE IF @RPT_WISE=2 
BEGIN
SET @SQLJOIN ="INNER JOIN  " +  @TEMPTABLE + " TT ON TT.CODE=ALM.LGR_ID"
SET @ORDERBYSQL="  ORDER BY AGENT,AGENTID,CITY,PARTY_CITYID,PARTY,LGR_ID,FLAG,DATE,BILL_NO"
END

ELSE IF @RPT_WISE=3 
BEGIN
SET @SQLJOIN ="INNER JOIN " +  @TEMPTABLE + " TT ON TT.CODE=SM.SALESMAN_ID"
SET @ORDERBYSQL=" ORDER BY  SALESMAN,SALESMANID,AGENT_CITYID,AGENT,FLAG,AGENTID,DATE,BILL_NO"
END

ELSE IF @RPT_WISE=4 
BEGIN
SET @SQLJOIN ="INNER JOIN " + @TEMPTABLE + " TT ON TT.CODE=CM.CITY_ID"
SET @ORDERBYSQL="  ORDER BY CITY,PARTY_CITYID,PARTY,LGR_ID"
END

ELSE IF @RPT_WISE=5 
BEGIN
SET @SQLJOIN ="INNER JOIN " + @TEMPTABLE + " TT ON TT.CODE=CGM.CUST_GRP_ID"
SET @ORDERBYSQL="  ORDER BY CUSTOMERGROUP,CUSTGRPID,CITY,PARTY_CITYID,PARTY,LGR_ID,FLAG,DATE,BILL_NO"
END
END


BEGIN 
IF @ONACCOUNT=1
SET @SQLONACCOUNT ="
UNION ALL
SELECT SUBSTRING('"+@DATABASENAME+"',1,LEN('"+@DATABASENAME+"')-5) AS DATABASENAME,0 AS VCODE,TM.TRAN_DOCNO AS  BILL_NO,'' AS JOBFLAG,TM.TRAN_DATE  AS DATE,0 AS BILL_AMOUNT,0 AS REC_AMOUNT,TM.TRAN_DATE  AS RECDATE,0 AS DISCOUNT,0 AS INTEREST,
0 AS INTREC,'P' AS FLAG, TD.CHEQUENO,TD.DDDATE AS CHEQUEDATE,
(CASE WHEN TD.TRAN_TYPE ='J' THEN (CASE WHEN TD.TRAN_DRCR='C'THEN (TD.PARTAMOUNT) ELSE CONVERT(NUMERIC(18,2),0) END) ELSE
(CASE WHEN TD.TRAN_DRCR='C'THEN (TD.PARTAMOUNT) ELSE CONVERT(NUMERIC(18,2),0) END) END)AS PARTAMOUNT,
TD.TRAN_ID,
LM.LGR_NAME AS PARTY,ALM.LGR_NAME AS AGENT,ISNULL(SM.SALESMAN_NAME,'') AS SALESMAN,ISNULL(CM.CITY_NAME,'') AS  CITY,ISNULL(CGM.CUST_GRP_NAME,'') AS CUSTOMERGROUP,TD.TRAN_TYPE,TD.TRAN_AMOUNT,CMP.CMP_ALIAS AS ALIAS,
'' AS LRNO,'' AS LRDATE,'' AS REMARK,ISNULL(ACM.CITY_NAME,'') AS AGENTCITTY,DATEDIFF(DAY,TM.TRAN_DATE,'"+@ASONDATE+"') AS OUTDAYS,ISNULL(LM.LGR_MOBILE,'') AS PARTYMOBILENO,ISNULL(ALM.LGR_MOBILE,'') AS AGENTMOBILENO,0 AS TDS_AMOUNT
,LM.LGR_ID,ALM.LGR_ID AS AGENTID,0 AS ADJINTEREST,'' AS ITEMNAME,
ISNULL(LM.LGR_PHONE1,'') AS LGR_PHONE1,ISNULL(LM.LGR_PHONE2,'') AS LGR_PHONE2
,ISNULL(ALM.LGR_PHONE1,'') AS AG_LGR_PHONE1,ISNULL(ALM.LGR_PHONE2,'') AS AG_LGR_PHONE2
,'' AS ITEMDETAIL,ISNULL(TM.BRDOCNO, '') AS BRDOCNO
,ISNULL(CM.CITY_ID,0) AS PARTY_CITYID,ISNULL(ALM.CITY_ID,0) AS AGENT_CITYID,
ISNULL(SM.SALESMAN_ID,0) AS SALESMANID,ISNULL(CGM.CUST_GRP_ID,0) AS CUSTGRPID,ISNULL(TM.NARRATION,'') AS PART_NARRATION
FROM " + @DATABASENAME + "TRAN_DETAIL TD 
INNER JOIN " + @DATABASENAME + "TRAN_MASTER TM ON TM.TRAN_ID=TD.TRAN_ID AND TM.TRAN_TYPE=TD.TRAN_TYPE AND TD.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @DATABASENAME + "LEDGER_MASTER LM ON LM.LGR_ID=TD.TRAN_DETAIL_ID
LEFT JOIN " + @DATABASENAME + "LEDGER_DETAIL LD ON LM.LGR_ID=LD.LGR_ID AND TD.CMP_CODE=LD.CMP_CODE
LEFT JOIN " + @DATABASENAME + "LEDGER_MASTER ALM ON ALM.LGR_ID=LD.AGENT_ID AND LM.LGR_TYPE = 'L'
LEFT JOIN " + @DATABASENAME + "CITY_MASTER CM ON LM.CITY_ID=CM.CITY_ID
LEFT JOIN " + @DATABASENAME + "CITY_MASTER ACM ON ALM.CITY_ID=ACM.CITY_ID
LEFT JOIN " + @DATABASENAME + "SALESMAN_MASTER SM ON SM.SALESMAN_ID=ALM.SALESMAN_ID
LEFT JOIN " + @DATABASENAME + "CUSTOMER_GROUP_MASTER CGM ON CGM.CUST_GRP_ID=LM.CUST_GRP_ID
LEFT JOIN " + @DATABASENAME + "COMPANY_MASTER CMP ON CMP.CMP_CODE=TM.CMP_CODE
INNER JOIN "+@DATABASENAME+" GROUP_MASTER GM ON GM.GRP_ID = LD.GRP_ID                            
" +  @SQLJOIN + "
WHERE TM.TRAN_DATE<='"+@ASONDATE+"' AND TD.PARTAMOUNT>0 AND (TD.SHOWPARTAMT=1 OR TD.SHOWPARTAMT IS NULL)  
AND (TD.TRAN_TYPE='BR'OR TD.TRAN_TYPE='CR' /*OR TD.TRAN_TYPE='SR'*/OR TD.TRAN_TYPE='YSR' OR TD.TRAN_TYPE='BP' OR TD.TRAN_TYPE='CP'  OR TD.TRAN_TYPE='DN' OR TD.TRAN_TYPE='CN' OR TD.TRAN_TYPE='J' )  AND TD.CMP_CODE IN(" + @CMP_CODE +")        
AND (TD.REC_TRANS=0 OR   TD.REC_TRANS IS NULL) AND GM.GRP_NAME = 'SUNDRY DEBTORS'
AND (TD.TRAN_DRCR='C')
UNION ALL "

SET @SQLONACCOUNT1 ="  
SELECT SUBSTRING('"+@DATABASENAME+"',1,LEN('"+@DATABASENAME+"')-5) AS DATABASENAME,0 AS VCODE,TM.TRAN_DOCNO AS  BILL_NO,'' AS JOBFLAG,TM.TRAN_DATE  AS DATE,0 AS BILL_AMOUNT,0 AS REC_AMOUNT,TM.TRAN_DATE  AS RECDATE,0 AS DISCOUNT,0 AS INTEREST,
0 AS INTREC,'P' AS FLAG, TD.CHEQUENO,TD.DDDATE AS CHEQUEDATE,
(CASE WHEN TD.TRAN_DRCR='C'THEN 0 ELSE 0-TD.PARTAMOUNT END)AS PARTAMOUNT,TD.TRAN_ID,
LM.LGR_NAME AS PARTY,ALM.LGR_NAME AS AGENT,ISNULL(SM.SALESMAN_NAME,'') AS SALESMAN,ISNULL(CM.CITY_NAME,'') AS  CITY,ISNULL(CGM.CUST_GRP_NAME,'') AS CUSTOMERGROUP,TD.TRAN_TYPE,TD.TRAN_AMOUNT,CMP.CMP_ALIAS AS ALIAS,
'' AS LRNO,'' AS LRDATE,'' AS REMARK,ISNULL(ACM.CITY_NAME,'') AS AGENTCITTY,DATEDIFF(DAY,TM.TRAN_DATE,'"+@ASONDATE+"') AS OUTDAYS,ISNULL(LM.LGR_MOBILE,'') AS PARTYMOBILENO,ISNULL(ALM.LGR_MOBILE,'') AS AGENTMOBILENO,0 AS TDS_AMOUNT
,LM.LGR_ID,ALM.LGR_ID AS AGENTID,0 AS ADJINTEREST,'' AS ITEMNAME,
ISNULL(LM.LGR_PHONE1,'') AS LGR_PHONE1,ISNULL(LM.LGR_PHONE2,'') AS LGR_PHONE2
,ISNULL(ALM.LGR_PHONE1,'') AS AG_LGR_PHONE1,ISNULL(ALM.LGR_PHONE2,'') AS AG_LGR_PHONE2
,'' AS ITEMDETAIL,ISNULL(TM.BRDOCNO, '') AS BRDOCNO
,ISNULL(CM.CITY_ID,0) AS PARTY_CITYID,ISNULL(ALM.CITY_ID,0) AS AGENT_CITYID,
ISNULL(SM.SALESMAN_ID,0) AS SALESMANID,ISNULL(CGM.CUST_GRP_ID,0) AS CUSTGRPID,ISNULL(TM.NARRATION,'') AS PART_NARRATION
FROM " + @DATABASENAME + "TRAN_DETAIL TD 
INNER JOIN " + @DATABASENAME + "TRAN_MASTER TM ON TM.TRAN_ID=TD.TRAN_ID AND TM.TRAN_TYPE=TD.TRAN_TYPE AND TD.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @DATABASENAME + "LEDGER_MASTER LM ON LM.LGR_ID=TD.TRAN_DETAIL_ID
LEFT JOIN " + @DATABASENAME + "LEDGER_DETAIL LD ON LM.LGR_ID=LD.LGR_ID AND TD.CMP_CODE=LD.CMP_CODE
LEFT JOIN " + @DATABASENAME + "LEDGER_MASTER ALM ON ALM.LGR_ID=LD.AGENT_ID  AND LM.LGR_TYPE = 'L'       
LEFT JOIN " + @DATABASENAME + "CITY_MASTER CM ON LM.CITY_ID=CM.CITY_ID
LEFT JOIN " + @DATABASENAME + "CITY_MASTER ACM ON ALM.CITY_ID=ACM.CITY_ID
LEFT JOIN " + @DATABASENAME + "SALESMAN_MASTER SM ON SM.SALESMAN_ID=ALM.SALESMAN_ID
LEFT JOIN " + @DATABASENAME + "CUSTOMER_GROUP_MASTER CGM ON CGM.CUST_GRP_ID=LM.CUST_GRP_ID
LEFT JOIN " + @DATABASENAME + "COMPANY_MASTER CMP ON CMP.CMP_CODE=TM.CMP_CODE
INNER JOIN "+@DATABASENAME+" GROUP_MASTER GM ON GM.GRP_ID = LD.GRP_ID                            
" +  @SQLJOIN + "
WHERE TM.TRAN_DATE<='"+@ASONDATE+"' AND (CASE WHEN TD.TRAN_DRCR='C'THEN 0 ELSE 0-TD.PARTAMOUNT END)<>0 AND (TD.SHOWPARTAMT=1 OR TD.SHOWPARTAMT IS NULL) 
AND (TD.TRAN_TYPE='BR'OR TD.TRAN_TYPE='CR' OR TD.TRAN_TYPE='SR'OR TD.TRAN_TYPE='YSR' OR TD.TRAN_TYPE='BP' OR TD.TRAN_TYPE='CP'  OR TD.TRAN_TYPE='DN' OR TD.TRAN_TYPE='CN' OR TD.TRAN_TYPE='J' )  AND TD.CMP_CODE IN(" + @CMP_CODE +")
AND (CONVERT(NVARCHAR,TM.TRAN_ID)+'JR') NOT IN (SELECT CONVERT(NVARCHAR,VCODE)+JOBFLAG FROM " + @DATABASENAME + "PARTYDETAIL WHERE JOBFLAG='JR')
AND (CONVERT(NVARCHAR,TM.TRAN_ID)+TM.TRAN_DOCNO+'DN') NOT IN (SELECT CONVERT(NVARCHAR,VCODE)+BILL_NO+JOBFLAG FROM " + @DATABASENAME + "PARTYDETAIL WHERE JOBFLAG='DN')
AND (CONVERT(NVARCHAR,TM.TRAN_ID)+TM.TRAN_DOCNO+'BP') NOT IN (SELECT CONVERT(NVARCHAR,VCODE)+BILL_NO+JOBFLAG FROM " + @DATABASENAME + " PARTYDETAIL WHERE JOBFLAG='BP')
AND (CONVERT(NVARCHAR,TM.TRAN_ID)+TM.TRAN_DOCNO+'CP') NOT IN (SELECT CONVERT(NVARCHAR,VCODE)+BILL_NO+JOBFLAG FROM " + @DATABASENAME + " PARTYDETAIL WHERE JOBFLAG='CP')
AND (TD.REC_TRANS=0 OR   TD.REC_TRANS IS NULL) AND GM.GRP_NAME = 'SUNDRY DEBTORS'
UNION ALL 
"
SET @SQLONACCOUNT2 ="  
SELECT SUBSTRING('"+@DATABASENAME+"',1,LEN('"+@DATABASENAME+"')-5) AS DATABASENAME,0 AS VCODE,'' AS  BILL_NO,'' AS JOBFLAG,AE.VDATE  AS DATE,0 AS BILL_AMOUNT,0 AS REC_AMOUNT,AE.VDATE  AS RECDATE,0 AS DISCOUNT,0 AS INTEREST,
0 AS INTREC,'P' AS FLAG, AE.CHQNO,AE.CHQDATE AS CHEQUEDATE,AE.PARTAMOUNT,AE.ADV_ID AS TRAN_ID,
LM.LGR_NAME AS PARTY,ALM.LGR_NAME AS AGENT,ISNULL(SM.SALESMAN_NAME,'') AS SALESMAN,ISNULL(CM.CITY_NAME,'') AS  CITY,ISNULL(CGM.CUST_GRP_NAME,'') AS CUSTOMERGROUP,AE.ENTRYTYPE AS TRAN_TYPE,AE.AMOUNT TRAN_AMOUNT,CMP.CMP_ALIAS AS ALIAS,
'' AS LRNO,'' AS LRDATE,'' AS REMARK,ISNULL(ACM.CITY_NAME,'') AS AGENTCITTY,DATEDIFF(DAY,AE.VDATE,'"+@ASONDATE+"') AS OUTDAYS,ISNULL(LM.LGR_MOBILE,'') AS PARTYMOBILENO,ISNULL(ALM.LGR_MOBILE,'') AS AGENTMOBILENO,0 AS TDS_AMOUNT
,LM.LGR_ID,ALM.LGR_ID AS AGENTID,0 AS ADJINTEREST,'' AS ITEMNAME,
ISNULL(LM.LGR_PHONE1,'') AS LGR_PHONE1,ISNULL(LM.LGR_PHONE2,'') AS LGR_PHONE2
,ISNULL(ALM.LGR_PHONE1,'') AS AG_LGR_PHONE1,ISNULL(ALM.LGR_PHONE2,'') AS AG_LGR_PHONE2
,'' AS ITEMDETAIL,'' AS BRDOCNO
,ISNULL(CM.CITY_ID,0) AS PARTY_CITYID,ISNULL(ALM.CITY_ID,0) AS AGENT_CITYID,
ISNULL(SM.SALESMAN_ID,0) AS SALESMANID,ISNULL(CGM.CUST_GRP_ID,0) AS CUSTGRPID,ISNULL(AE.REMARK,'') AS PART_NARRATION
FROM " + @DATABASENAME + "ADVANCE_ENTRY AE         
INNER JOIN " + @DATABASENAME + "LEDGER_MASTER LM ON LM.LGR_ID=AE.LGR_ID
LEFT JOIN " + @DATABASENAME + "LEDGER_DETAIL LD ON LM.LGR_ID=LD.LGR_ID AND AE.CMP_CODE=LD.CMP_CODE
LEFT JOIN " + @DATABASENAME + "LEDGER_MASTER ALM ON ALM.LGR_ID=LD.AGENT_ID
LEFT JOIN " + @DATABASENAME + "CITY_MASTER CM ON LM.CITY_ID=CM.CITY_ID
LEFT JOIN " + @DATABASENAME + "SALESMAN_MASTER SM ON SM.SALESMAN_ID=ALM.SALESMAN_ID
LEFT JOIN " + @DATABASENAME + "CITY_MASTER ACM ON ALM.CITY_ID=ACM.CITY_ID
LEFT JOIN " + @DATABASENAME + "CUSTOMER_GROUP_MASTER CGM ON CGM.CUST_GRP_ID=LM.CUST_GRP_ID      
LEFT JOIN " + @DATABASENAME + "COMPANY_MASTER CMP ON CMP.CMP_CODE=AE.CMP_CODE
" +  @SQLJOIN + "
WHERE AE.VDATE<='"+@ASONDATE+"' AND AE.PARTAMOUNT>0 AND AE.CMP_CODE IN(" + @CMP_CODE +")"

SET @SQLONACCOUNT6=" UNION ALL
SELECT SUBSTRING('" + @DATABASENAME + "',1,LEN('" + @DATABASENAME + "')-5) AS DATABASENAME,0 AS VCODE,TM.TRAN_DOCNO AS  BILL_NO,'' AS JOBFLAG,TM.TRAN_DATE  AS DATE,0 AS BILL_AMOUNT,0 AS REC_AMOUNT,TM.TRAN_DATE  AS RECDATE,0 AS DISCOUNT,0 AS INTEREST,
0 AS INTREC,'P' AS FLAG, TD.CHEQUENO,TD.DDDATE AS CHEQUEDATE,
(CASE WHEN TD.TRAN_TYPE ='J' THEN (CASE WHEN TD.TRAN_DRCR='C'THEN (TD.PARTAMOUNT) ELSE 0 END) ELSE
(CASE WHEN TD.TRAN_DRCR='C'THEN (TM.TRAN_AMOUNT) ELSE TM.TRAN_AMOUNT END) END)AS PARTAMOUNT,
TD.TRAN_ID,
LM.LGR_NAME AS PARTY,ALM.LGR_NAME AS AGENT,SM.SALESMAN_NAME AS SALESMAN,CM.CITY_NAME AS  CITY,CGM.CUST_GRP_NAME AS CUSTOMERGROUP,TD.TRAN_TYPE,TM.TRAN_AMOUNT,CMP.CMP_ALIAS AS ALIAS,
'' AS LRNO,'' AS LRDATE,'' AS REMARK,ACM.CITY_NAME AS AGENTCITTY,DATEDIFF(DAY,TM.TRAN_DATE,'"+@ASONDATE+"') AS OUTDAYS,ISNULL(LM.Lgr_Mobile,'') AS PARTYMOBILENO,ISNULL(ALM.Lgr_Mobile,'') AS AGENTMOBILENO,0 AS TDS_AMOUNT
,LM.LGR_ID,ALM.LGR_ID AS AGENTID,0 AS ADJINTEREST,'' AS ITEMNAME,
ISNULL(LM.LGR_PHONE1,'') AS LGR_PHONE1,ISNULL(LM.LGR_PHONE2,'') AS LGR_PHONE2
,ISNULL(ALM.LGR_PHONE1,'') AS AG_LGR_PHONE1,ISNULL(ALM.LGR_PHONE2,'') AS AG_LGR_PHONE2
,'' AS ITEMDETAIL,ISNULL(TM.BRDOCNO, '')  AS BRDOCNO
,ISNULL(CM.CITY_ID,0) AS PARTY_CITYID,ISNULL(ALM.CITY_ID,0) AS AGENT_CITYID,
ISNULL(SM.SALESMAN_ID,0) AS SALESMANID,ISNULL(CGM.CUST_GRP_ID,0) AS CUSTGRPID,ISNULL(TM.NARRATION,'') AS PART_NARRATION
FROM " + @DATABASENAME + "TRAN_DETAIL TD 
INNER JOIN " + @DATABASENAME + "TRAN_MASTER TM ON TM.TRAN_ID=TD.TRAN_ID AND TM.TRAN_TYPE=TD.TRAN_TYPE AND TD.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @DATABASENAME + "LEDGER_MASTER LM ON LM.LGR_ID=TM.TRAN_MASTER_ID
LEFT JOIN " + @DATABASENAME + "LEDGER_DETAIL LD ON LM.LGR_ID=LD.LGR_ID AND TD.CMP_CODE=LD.CMP_CODE
LEFT JOIN " + @DATABASENAME + "LEDGER_MASTER ALM ON ALM.LGR_ID=LD.AGENT_ID AND LM.LGR_TYPE = 'L'
LEFT JOIN " + @DATABASENAME + "CITY_MASTER CM ON LM.CITY_ID=CM.CITY_ID
LEFT JOIN " + @DATABASENAME + "CITY_MASTER ACM ON ALM.CITY_ID=ACM.CITY_ID
LEFT JOIN " + @DATABASENAME + "SALESMAN_MASTER SM ON SM.SALESMAN_ID=ALM.SALESMAN_ID
LEFT JOIN " + @DATABASENAME + "CUSTOMER_GROUP_MASTER CGM ON CGM.CUST_GRP_ID=LM.CUST_GRP_ID
LEFT JOIN " + @DATABASENAME + "COMPANY_MASTER CMP ON CMP.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @DATABASENAME + " GROUP_MASTER GM ON GM.GRP_ID = LD.GRP_ID                            
" +  @SQLJOIN + "
WHERE TM.TRAN_DATE<='"+@ASONDATE+"' AND TD.PARTAMOUNT>0 AND (TM.SHOWPARTAMT=1 OR TM.SHOWPARTAMT IS NULL)  
AND ( TM.TRAN_TYPE IN ('SR','GCN','GDN') )  AND TD.CMP_CODE IN(" + @CMP_CODE +")        
AND (TM.REC_TRANS=0 OR   TM.REC_TRANS IS NULL) AND GM.GRP_NAME = 'SUNDRY DEBTORS'
AND (TM.TRAN_DRCR='C')
"

BEGIN
IF  @PREVDATABASE!=""
BEGIN
SET @SQLONACCOUNT3 =" 
UNION ALL
SELECT SUBSTRING('"+@PREVDATABASE+"',1,LEN('"+@PREVDATABASE+"')-5) AS DATABASENAME,0 AS VCODE,'' AS  BILL_NO,'' AS JOBFLAG,AE.VDATE  AS DATE,0 AS BILL_AMOUNT,0 AS REC_AMOUNT,AE.VDATE  AS RECDATE,0 AS DISCOUNT,0 AS INTEREST,
0 AS INTREC,'P' AS FLAG, AE.CHQNO,AE.CHQDATE AS CHEQUEDATE,AE.PARTAMOUNT,AE.ADV_ID AS TRAN_ID,
LM.LGR_NAME AS PARTY,ALM.LGR_NAME AS AGENT,ISNULL(SM.SALESMAN_NAME,'') AS SALESMAN,ISNULL(CM.CITY_NAME,'') AS  CITY,ISNULL(CGM.CUST_GRP_NAME,'') AS CUSTOMERGROUP,AE.ENTRYTYPE AS TRAN_TYPE,AE.AMOUNT TRAN_AMOUNT,CMP.CMP_ALIAS AS ALIAS,
'' AS LRNO,'' AS LRDATE,'' AS REMARK,ISNULL(ACM.CITY_NAME,'') AS AGENTCITTY,DATEDIFF(DAY,AE.VDATE,'"+@ASONDATE+"') AS OUTDAYS,ISNULL(LM.LGR_MOBILE,'') AS PARTYMOBILENO,ISNULL(ALM.LGR_MOBILE,'') AS AGENTMOBILENO,0 AS TDS_AMOUNT
,LM.LGR_ID,ALM.LGR_ID AS AGENTID,0 AS ADJINTEREST,'' AS ITEMNAME,
ISNULL(LM.LGR_PHONE1,'') AS LGR_PHONE1,ISNULL(LM.LGR_PHONE2,'') AS LGR_PHONE2
,ISNULL(ALM.LGR_PHONE1,'') AS AG_LGR_PHONE1,ISNULL(ALM.LGR_PHONE2,'') AS AG_LGR_PHONE2
,'' AS ITEMDETAIL,'' AS BRDOCNO
,ISNULL(CM.CITY_ID,0) AS PARTY_CITYID,ISNULL(ALM.CITY_ID,0) AS AGENT_CITYID,
ISNULL(SM.SALESMAN_ID,0) AS SALESMANID,ISNULL(CGM.CUST_GRP_ID,0) AS CUSTGRPID,ISNULL(AE.REMARK,'') AS PART_NARRATION
FROM " + @PREVDATABASE + "ADVANCE_ENTRY AE         
INNER JOIN " + @PREVDATABASE + "LEDGER_MASTER LM ON LM.LGR_ID=AE.LGR_ID
LEFT JOIN " + @PREVDATABASE + "LEDGER_DETAIL LD ON LM.LGR_ID=LD.LGR_ID AND AE.CMP_CODE=LD.CMP_CODE
LEFT JOIN " + @PREVDATABASE + "LEDGER_MASTER ALM ON ALM.LGR_ID=LD.AGENT_ID
LEFT JOIN " + @PREVDATABASE + "CITY_MASTER CM ON LM.CITY_ID=CM.CITY_ID
LEFT JOIN " + @PREVDATABASE + "SALESMAN_MASTER SM ON SM.SALESMAN_ID=ALM.SALESMAN_ID
LEFT JOIN " + @PREVDATABASE + "CITY_MASTER ACM ON ALM.CITY_ID=ACM.CITY_ID
LEFT JOIN " + @PREVDATABASE + "CUSTOMER_GROUP_MASTER CGM ON CGM.CUST_GRP_ID=LM.CUST_GRP_ID      
LEFT JOIN " + @PREVDATABASE + "COMPANY_MASTER CMP ON CMP.CMP_CODE=AE.CMP_CODE
" +  @SQLJOIN + "
WHERE AE.VDATE<='"+@ASONDATE+"' AND AE.PARTAMOUNT>0 AND AE.CMP_CODE IN(" + @CMP_CODE +")
AND (AE.REC_TRANS=0 OR   AE.REC_TRANS IS NULL)
"
SET @SQLONACCOUNT4 ="
UNION ALL
SELECT SUBSTRING('"+@PREVDATABASE+"',1,LEN('"+@DATABASENAME+"')-5) AS DATABASENAME,0 AS VCODE,TM.TRAN_DOCNO AS  BILL_NO,'' AS JOBFLAG,TM.TRAN_DATE  AS DATE,0 AS BILL_AMOUNT,0 AS REC_AMOUNT,TM.TRAN_DATE  AS RECDATE,0 AS DISCOUNT,0 AS INTEREST,
0 AS INTREC,'P' AS FLAG, TD.CHEQUENO,TD.DDDATE AS CHEQUEDATE,
(CASE WHEN TD.TRAN_TYPE ='J' THEN (CASE WHEN TD.TRAN_DRCR='C'THEN (TD.PARTAMOUNT) ELSE CONVERT(NUMERIC(18,2),0) END) ELSE
(CASE WHEN TD.TRAN_DRCR='C'THEN (TD.PARTAMOUNT) ELSE CONVERT(NUMERIC(18,2),0) END) END)AS PARTAMOUNT,
TD.TRAN_ID,
LM.LGR_NAME AS PARTY,ALM.LGR_NAME AS AGENT,ISNULL(SM.SALESMAN_NAME,'') AS SALESMAN,ISNULL(CM.CITY_NAME,'') AS  CITY,ISNULL(CGM.CUST_GRP_NAME,'') AS CUSTOMERGROUP,TD.TRAN_TYPE,TD.TRAN_AMOUNT,CMP.CMP_ALIAS AS ALIAS,
'' AS LRNO,'' AS LRDATE,'' AS REMARK,ISNULL(ACM.CITY_NAME,'') AS AGENTCITTY,DATEDIFF(DAY,TM.TRAN_DATE,'"+@ASONDATE+"') AS OUTDAYS,ISNULL(LM.LGR_MOBILE,'') AS PARTYMOBILENO,ISNULL(ALM.LGR_MOBILE,'') AS AGENTMOBILENO,0 AS TDS_AMOUNT
,LM.LGR_ID,ALM.LGR_ID AS AGENTID,0 AS ADJINTEREST,'' AS ITEMNAME,
ISNULL(LM.LGR_PHONE1,'') AS LGR_PHONE1,ISNULL(LM.LGR_PHONE2,'') AS LGR_PHONE2
,ISNULL(ALM.LGR_PHONE1,'') AS AG_LGR_PHONE1,ISNULL(ALM.LGR_PHONE2,'') AS AG_LGR_PHONE2
,'' AS ITEMDETAIL,ISNULL(TM.BRDOCNO, '') AS BRDOCNO
,ISNULL(CM.CITY_ID,0) AS PARTY_CITYID,ISNULL(ALM.CITY_ID,0) AS AGENT_CITYID,
ISNULL(SM.SALESMAN_ID,0) AS SALESMANID,ISNULL(CGM.CUST_GRP_ID,0) AS CUSTGRPID,ISNULL(TM.NARRATION,'') AS PART_NARRATION
FROM " + @PREVDATABASE + "TRAN_DETAIL TD 
INNER JOIN " + @PREVDATABASE + "TRAN_MASTER TM ON TM.TRAN_ID=TD.TRAN_ID AND TM.TRAN_TYPE=TD.TRAN_TYPE AND TD.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @PREVDATABASE + "LEDGER_MASTER LM ON LM.LGR_ID=TD.TRAN_DETAIL_ID
LEFT JOIN " + @PREVDATABASE + "LEDGER_DETAIL LD ON LM.LGR_ID=LD.LGR_ID AND TD.CMP_CODE=LD.CMP_CODE
LEFT JOIN " + @PREVDATABASE + "LEDGER_MASTER ALM ON ALM.LGR_ID=LD.AGENT_ID AND LM.LGR_TYPE = 'L'
LEFT JOIN " + @PREVDATABASE + "CITY_MASTER CM ON LM.CITY_ID=CM.CITY_ID
LEFT JOIN " + @PREVDATABASE + "CITY_MASTER ACM ON ALM.CITY_ID=ACM.CITY_ID
LEFT JOIN " + @PREVDATABASE + "SALESMAN_MASTER SM ON SM.SALESMAN_ID=ALM.SALESMAN_ID
LEFT JOIN " + @PREVDATABASE + "CUSTOMER_GROUP_MASTER CGM ON CGM.CUST_GRP_ID=LM.CUST_GRP_ID
LEFT JOIN " + @PREVDATABASE + "COMPANY_MASTER CMP ON CMP.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @PREVDATABASE + " GROUP_MASTER GM ON GM.GRP_ID = LD.GRP_ID                            
" +  @SQLJOIN + "
WHERE TM.TRAN_DATE<='"+@ASONDATE+"' AND TD.PARTAMOUNT>0 AND (TD.SHOWPARTAMT=1 OR TD.SHOWPARTAMT IS NULL)  
AND (TD.TRAN_TYPE='BR'OR TD.TRAN_TYPE='CR' OR TD.TRAN_TYPE='SR'OR TD.TRAN_TYPE='YSR' OR TD.TRAN_TYPE='BP' OR TD.TRAN_TYPE='CP'  OR TD.TRAN_TYPE='DN' OR TD.TRAN_TYPE='CN' OR TD.TRAN_TYPE='J' )  AND TD.CMP_CODE IN(" + @CMP_CODE +")        
AND (TD.REC_TRANS=0 OR   TD.REC_TRANS IS NULL) AND GM.GRP_NAME = 'SUNDRY DEBTORS'
AND (TD.TRAN_DRCR='C')
UNION ALL "

SET @SQLONACCOUNT5 ="  
SELECT SUBSTRING('"+@PREVDATABASE+"',1,LEN('"+@DATABASENAME+"')-5) AS DATABASENAME,0 AS VCODE,TM.TRAN_DOCNO AS  BILL_NO,'' AS JOBFLAG,TM.TRAN_DATE  AS DATE,0 AS BILL_AMOUNT,0 AS REC_AMOUNT,TM.TRAN_DATE  AS RECDATE,0 AS DISCOUNT,0 AS INTEREST,
0 AS INTREC,'P' AS FLAG, TD.CHEQUENO,TD.DDDATE AS CHEQUEDATE,
(CASE WHEN TD.TRAN_DRCR='C'THEN 0 ELSE 0-TD.PARTAMOUNT END)AS PARTAMOUNT,TD.TRAN_ID,
LM.LGR_NAME AS PARTY,ALM.LGR_NAME AS AGENT,ISNULL(SM.SALESMAN_NAME,'') AS SALESMAN,ISNULL(CM.CITY_NAME,'') AS  CITY,ISNULL(CGM.CUST_GRP_NAME,'') AS CUSTOMERGROUP,TD.TRAN_TYPE,TD.TRAN_AMOUNT,CMP.CMP_ALIAS AS ALIAS,
'' AS LRNO,'' AS LRDATE,'' AS REMARK,ISNULL(ACM.CITY_NAME,'') AS AGENTCITTY,DATEDIFF(DAY,TM.TRAN_DATE,'"+@ASONDATE+"') AS OUTDAYS,ISNULL(LM.LGR_MOBILE,'') AS PARTYMOBILENO,ISNULL(ALM.LGR_MOBILE,'') AS AGENTMOBILENO,0 AS TDS_AMOUNT
,LM.LGR_ID,ALM.LGR_ID AS AGENTID,0 AS ADJINTEREST,'' AS ITEMNAME,
ISNULL(LM.LGR_PHONE1,'') AS LGR_PHONE1,ISNULL(LM.LGR_PHONE2,'') AS LGR_PHONE2
,ISNULL(ALM.LGR_PHONE1,'') AS AG_LGR_PHONE1,ISNULL(ALM.LGR_PHONE2,'') AS AG_LGR_PHONE2
,'' AS ITEMDETAIL,ISNULL(TM.BRDOCNO, '') AS BRDOCNO
,ISNULL(CM.CITY_ID,0) AS PARTY_CITYID,ISNULL(ALM.CITY_ID,0) AS AGENT_CITYID,
ISNULL(SM.SALESMAN_ID,0) AS SALESMANID,ISNULL(CGM.CUST_GRP_ID,0) AS CUSTGRPID,ISNULL(TM.NARRATION,'') AS PART_NARRATION
FROM " + @PREVDATABASE + "TRAN_DETAIL TD 
INNER JOIN " + @PREVDATABASE + "TRAN_MASTER TM ON TM.TRAN_ID=TD.TRAN_ID AND TM.TRAN_TYPE=TD.TRAN_TYPE AND TD.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @PREVDATABASE + "LEDGER_MASTER LM ON LM.LGR_ID=TD.TRAN_DETAIL_ID
LEFT JOIN " + @PREVDATABASE + "LEDGER_DETAIL LD ON LM.LGR_ID=LD.LGR_ID AND TD.CMP_CODE=LD.CMP_CODE
LEFT JOIN " + @PREVDATABASE + "LEDGER_MASTER ALM ON ALM.LGR_ID=LD.AGENT_ID   AND LM.LGR_TYPE = 'L'      
LEFT JOIN " + @PREVDATABASE + "CITY_MASTER CM ON LM.CITY_ID=CM.CITY_ID
LEFT JOIN " + @PREVDATABASE + "CITY_MASTER ACM ON ALM.CITY_ID=ACM.CITY_ID
LEFT JOIN " + @PREVDATABASE + "SALESMAN_MASTER SM ON SM.SALESMAN_ID=ALM.SALESMAN_ID
LEFT JOIN " + @PREVDATABASE + "CUSTOMER_GROUP_MASTER CGM ON CGM.CUST_GRP_ID=LM.CUST_GRP_ID
LEFT JOIN " + @PREVDATABASE + "COMPANY_MASTER CMP ON CMP.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @PREVDATABASE + " GROUP_MASTER GM ON GM.GRP_ID = LD.GRP_ID                            
" +  @SQLJOIN + "
WHERE TM.TRAN_DATE<='"+@ASONDATE+"' AND (CASE WHEN TD.TRAN_DRCR='C'THEN 0 ELSE 0-TD.PARTAMOUNT END)<>0 AND (TD.SHOWPARTAMT=1 OR TD.SHOWPARTAMT IS NULL) 
AND (TD.TRAN_TYPE='BR'OR TD.TRAN_TYPE='CR' OR TD.TRAN_TYPE='SR'OR TD.TRAN_TYPE='YSR' OR TD.TRAN_TYPE='BP' OR TD.TRAN_TYPE='CP'  OR TD.TRAN_TYPE='DN' OR TD.TRAN_TYPE='CN' OR TD.TRAN_TYPE='J' )  AND TD.CMP_CODE IN(" + @CMP_CODE +")
AND (CONVERT(NVARCHAR,TM.TRAN_ID)+'JR') NOT IN (SELECT CONVERT(NVARCHAR,VCODE)+JOBFLAG FROM " + @PREVDATABASE + "PARTYDETAIL WHERE JOBFLAG='JR')
AND (CONVERT(NVARCHAR,TM.TRAN_ID)+TM.TRAN_DOCNO+'DN') NOT IN (SELECT CONVERT(NVARCHAR,VCODE)+BILL_NO+JOBFLAG FROM " + @PREVDATABASE + "PARTYDETAIL WHERE JOBFLAG='DN')
AND (CONVERT(NVARCHAR,TM.TRAN_ID)+TM.TRAN_DOCNO+'BP') NOT IN (SELECT CONVERT(NVARCHAR,VCODE)+BILL_NO+JOBFLAG FROM " + @PREVDATABASE + " PARTYDETAIL WHERE JOBFLAG='BP')
AND (CONVERT(NVARCHAR,TM.TRAN_ID)+TM.TRAN_DOCNO+'CP') NOT IN (SELECT CONVERT(NVARCHAR,VCODE)+BILL_NO+JOBFLAG FROM " + @PREVDATABASE + " PARTYDETAIL WHERE JOBFLAG='CP')	 
AND (TD.REC_TRANS=0 OR   TD.REC_TRANS IS NULL) AND GM.GRP_NAME = 'SUNDRY DEBTORS'                         
"     
SET @SQLONACCOUNT7=" UNION ALL
SELECT SUBSTRING('" + @PREVDATABASE + "',1,LEN('" + @DATABASENAME + "')-5) AS DATABASENAME,0 AS VCODE,TM.TRAN_DOCNO AS  BILL_NO,'' AS JOBFLAG,TM.TRAN_DATE  AS DATE,0 AS BILL_AMOUNT,0 AS REC_AMOUNT,TM.TRAN_DATE  AS RECDATE,0 AS DISCOUNT,0 AS INTEREST,
0 AS INTREC,'P' AS FLAG, TD.CHEQUENO,TD.DDDATE AS CHEQUEDATE,
(CASE WHEN TD.TRAN_TYPE ='J' THEN (CASE WHEN TD.TRAN_DRCR='C'THEN (TD.PARTAMOUNT) ELSE 0 END) ELSE
(CASE WHEN TD.TRAN_DRCR='C'THEN (TM.TRAN_AMOUNT) ELSE TM.TRAN_AMOUNT END) END)AS PARTAMOUNT,
TD.TRAN_ID,
LM.LGR_NAME AS PARTY,ALM.LGR_NAME AS AGENT,SM.SALESMAN_NAME AS SALESMAN,CM.CITY_NAME AS  CITY,CGM.CUST_GRP_NAME AS CUSTOMERGROUP,TD.TRAN_TYPE,TM.TRAN_AMOUNT,CMP.CMP_ALIAS AS ALIAS,
'' AS LRNO,'' AS LRDATE,'' AS REMARK,ACM.CITY_NAME AS AGENTCITTY,DATEDIFF(DAY,TM.TRAN_DATE,'"+@ASONDATE+"') AS OUTDAYS,ISNULL(LM.Lgr_Mobile,'') AS PARTYMOBILENO,ISNULL(ALM.Lgr_Mobile,'') AS AGENTMOBILENO,0 AS TDS_AMOUNT
,LM.LGR_ID,ALM.LGR_ID AS AGENTID,0 AS ADJINTEREST,'' AS ITEMNAME,
ISNULL(LM.LGR_PHONE1,'') AS LGR_PHONE1,ISNULL(LM.LGR_PHONE2,'') AS LGR_PHONE2
,ISNULL(ALM.LGR_PHONE1,'') AS AG_LGR_PHONE1,ISNULL(ALM.LGR_PHONE2,'') AS AG_LGR_PHONE2
,'' AS ITEMDETAIL,ISNULL(TM.BRDOCNO, '') AS BRDOCNO
,ISNULL(CM.CITY_ID,0) AS PARTY_CITYID,ISNULL(ALM.CITY_ID,0) AS AGENT_CITYID,
ISNULL(SM.SALESMAN_ID,0) AS SALESMANID,ISNULL(CGM.CUST_GRP_ID,0) AS CUSTGRPID,ISNULL(TM.NARRATION,'') AS PART_NARRATION
FROM " + @PREVDATABASE + "TRAN_DETAIL TD 
INNER JOIN " + @PREVDATABASE + "TRAN_MASTER TM ON TM.TRAN_ID=TD.TRAN_ID AND TM.TRAN_TYPE=TD.TRAN_TYPE AND TD.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @PREVDATABASE + "LEDGER_MASTER LM ON LM.LGR_ID=TM.TRAN_MASTER_ID
LEFT JOIN " + @PREVDATABASE + "LEDGER_DETAIL LD ON LM.LGR_ID=LD.LGR_ID AND TD.CMP_CODE=LD.CMP_CODE
LEFT JOIN " + @PREVDATABASE + "LEDGER_MASTER ALM ON ALM.LGR_ID=LD.AGENT_ID AND LM.LGR_TYPE = 'L'
LEFT JOIN " + @PREVDATABASE + "CITY_MASTER CM ON LM.CITY_ID=CM.CITY_ID
LEFT JOIN " + @PREVDATABASE + "CITY_MASTER ACM ON ALM.CITY_ID=ACM.CITY_ID
LEFT JOIN " + @PREVDATABASE + "SALESMAN_MASTER SM ON SM.SALESMAN_ID=ALM.SALESMAN_ID
LEFT JOIN " + @PREVDATABASE + "CUSTOMER_GROUP_MASTER CGM ON CGM.CUST_GRP_ID=LM.CUST_GRP_ID
LEFT JOIN " + @PREVDATABASE + "COMPANY_MASTER CMP ON CMP.CMP_CODE=TM.CMP_CODE
INNER JOIN " + @PREVDATABASE + " GROUP_MASTER GM ON GM.GRP_ID = LD.GRP_ID                            
" +  @SQLJOIN + "
WHERE TM.TRAN_DATE<='"+@ASONDATE+"' AND TD.PARTAMOUNT>0 AND (TM.SHOWPARTAMT=1 OR TM.SHOWPARTAMT IS NULL)  
AND ( TM.TRAN_TYPE IN ('SR','GCN','GDN') )  AND TD.CMP_CODE IN(" + @CMP_CODE +")        
AND (TM.REC_TRANS=0 OR   TM.REC_TRANS IS NULL) AND GM.GRP_NAME = 'SUNDRY DEBTORS'
AND (TM.TRAN_DRCR='C')
"      
END
END /* END OF PREVIOUS YEAR CONDITION */
END /* END OF ONACCOUNT  CONDITION */
BEGIN
IF @ONACCOUNT=0
BEGIN
SET @SQLONACCOUNT =""
SET @SQLONACCOUNT1 =""
SET @SQLONACCOUNT2 =""
SET @SQLONACCOUNT3=""
SET @SQLONACCOUNT4=""
SET @SQLONACCOUNT5="" 
SET @SQLONACCOUNT6=""   
SET @SQLONACCOUNT7 =""
END
END
SET @SQL=""
BEGIN
IF(@RPT_TYPE=1)
SET @CONDITION=" AND (AM.BILLNO+AM.FLAG+CONVERT(NVARCHAR(50),AM.VCODE))   IN (SELECT (AM1.BILLNO+AM1.FLAG+CONVERT(NVARCHAR(50),AM1.VCODE)) FROM " + @DATABASENAME + "ADJMASTER AM1 WHERE AM1.RECDATE<='"+ @ASONDATE + "' AND AM1.PAID=1  AND AM1.CMP_CODE IN ("+@CMP_CODE+") AND AM.CMP_CODE=AM1.CMP_CODE AND AM.FLAG=AM1.FLAG)"
END
BEGIN
IF(@RPT_TYPE=2)
SET @CONDITION=" AND (AM.BILLNO+AM.FLAG+CONVERT(NVARCHAR(50),AM.VCODE)) NOT IN (SELECT (AM1.BILLNO+AM1.FLAG+CONVERT(NVARCHAR(50),AM1.VCODE)) FROM " + @DATABASENAME + "ADJMASTER AM1 WHERE AM1.RECDATE<='"+ @ASONDATE +"' AND AM1.PAID=1 AND AM1.CMP_CODE IN ("+@CMP_CODE+") AND AM.CMP_CODE=AM1.CMP_CODE AND AM.FLAG=AM1.FLAG) "
END
BEGIN
IF(@DUEPENDING=1)
SET @CONDITION=" AND PD.BILL_AMOUNT=PD.PENDING_AMOUNT "
END
IF @DAYS!="0" 
BEGIN
SET   @CONDITION=@CONDITION +" AND DATEDIFF(DAY,PD.DATE,'"+@ASONDATE+"')>="+@DAYS
END

SET @SQL="

SELECT DATABASENAME,VCODE,BILL_NO,DATE,JOBFLAG,BILL_AMOUNT,REC_AMOUNT,RECDATE,DISCOUNT,INTEREST,INTREC,FLAG,
CHEQUENO,CHEQUEDATE,PARTAMOUNT,TRAN_ID,PARTY,AGENT,SALESMAN,CITY,CUSTOMERGROUP,TRAN_TYPE,TRAN_AMOUNT,ALIAS,
LRNO,LRDATE,REMARK,AGENTCITTY,OUTDAYS,PARTYMOBILENO,AGENTMOBILENO,TDS_AMOUNT,LGR_ID,AGENTID,ADJINTEREST,
ITEMNAME,LGR_PHONE1,LGR_PHONE2,AG_LGR_PHONE1,AG_LGR_PHONE2,ITEMDETAIL,CONVERT(NVARCHAR,ISNULL(BRDOCNO,'NULL')) AS BRDOCNO
,PARTY_CITYID,AGENT_CITYID,SALESMANID,CUSTGRPID,PART_NARRATION
FROM(
SELECT SUBSTRING('"+@DATABASENAME+"',1,LEN('"+@DATABASENAME+"')-5) AS DATABASENAME,PD.VCODE,PD.BILL_NO,PD.JOBFLAG,PD.DATE,ISNULL(PD.BILL_AMOUNT,0)BILL_AMOUNT,ISNULL(AM.ADJUSTAMT,0) AS REC_AMOUNT,AM.RECDATE,ISNULL(AM.TOTAL,0)AS DISCOUNT,ISNULL(AM.INTEREST,0)AS INTEREST,ISNULL(AM.INTREC,0) AS INTREC,'D' AS FLAG,AM.CHEQUENO AS CHEQUENO,AM.CHEQUEDATE AS CHEQUEDATE, CONVERT(NUMERIC(18,2),0) AS PARTAMOUNT,0 AS TRAN_ID,
LM.LGR_NAME AS PARTY,ALM.LGR_NAME AS AGENT,ISNULL(SM.SALESMAN_NAME,'') AS SALESMAN,ISNULL(CM.CITY_NAME,'') AS CITY,ISNULL(CGM.CUST_GRP_NAME,'') AS CUSTOMERGROUP,'AA' AS TRAN_TYPE,0 AS TRAN_AMOUNT,CMP.CMP_ALIAS AS ALIAS,
PD.LRNO AS LRNO,PD.LRDATE AS LRDATE,AM.REMARK,ISNULL(ACM.CITY_NAME,'') AS AGENTCITTY,DATEDIFF(DAY,PD.DATE,'"+@ASONDATE+"') AS OUTDAYS,ISNULL(LM.LGR_MOBILE,'') AS PARTYMOBILENO,ISNULL(ALM.LGR_MOBILE,'') AS AGENTMOBILENO, 0 AS TDS_AMOUNT
,LM.LGR_ID,ALM.LGR_ID AS AGENTID,ISNULL(AM.ADJINTEREST,0) AS ADJINTEREST,ISNULL(PD.ITEMNAME,'')AS ITEMNAME,
ISNULL(LM.LGR_PHONE1,'') AS LGR_PHONE1,ISNULL(LM.LGR_PHONE2,'') AS LGR_PHONE2
,ISNULL(ALM.LGR_PHONE1,'') AS AG_LGR_PHONE1,ISNULL(ALM.LGR_PHONE2,'') AS AG_LGR_PHONE2
,ISNULL(PD.ITEMDETAIL,'')AS ITEMDETAIL,'' AS BRDOCNO
,ISNULL(CM.CITY_ID,0) AS PARTY_CITYID,ISNULL(ALM.CITY_ID,0) AS AGENT_CITYID,
ISNULL(SM.SALESMAN_ID,0) AS SALESMANID,ISNULL(CGM.CUST_GRP_ID,0) AS CUSTGRPID,CONVERT(NVARCHAR(500),'') AS PART_NARRATION

FROM " + @DATABASENAME + " PARTYDETAIL PD 
LEFT JOIN " + @DATABASENAME + " ADJMASTER AM ON AM.BILLNO=PD.BILL_NO AND AM.FLAG=PD.JOBFLAG AND AM.CMP_CODE=PD.CMP_CODE AND PD.VCODE=AM.VCODE  AND AM.RECDATE<='"+ @ASONDATE +"'
LEFT JOIN " + @DATABASENAME + "LEDGER_MASTER LM ON LM.LGR_ID=PD.LGR_ID
LEFT JOIN " + @DATABASENAME + "LEDGER_MASTER ALM ON ALM.LGR_ID=PD.AGENT_ID
LEFT JOIN " + @DATABASENAME + "SALESMAN_MASTER SM ON SM.SALESMAN_ID=ALM.SALESMAN_ID
LEFT JOIN " + @DATABASENAME + "CITY_MASTER CM ON CM.CITY_ID=LM.CITY_ID
LEFT JOIN " + @DATABASENAME + "CITY_MASTER ACM ON ALM.CITY_ID=ACM.CITY_ID
LEFT JOIN " + @DATABASENAME + "CUSTOMER_GROUP_MASTER CGM ON CGM.CUST_GRP_ID=LM.CUST_GRP_ID
LEFT JOIN " + @DATABASENAME + "COMPANY_MASTER CMP ON CMP.CMP_CODE=PD.CMP_CODE
" +  @SQLJOIN + "
WHERE  PD.DATE<='"+@ASONDATE+"' AND PD.CMP_CODE IN("+ @CMP_CODE +")" +  @CONDITION  +"

"

EXEC(@SQL+ @SQLONACCOUNT+@SQLONACCOUNT1+@SQLONACCOUNT2+@SQLONACCOUNT6+ @SQLONACCOUNT3+ @SQLONACCOUNT4+ @SQLONACCOUNT5+ @SQLONACCOUNT7+") AS DETAIL "+@ORDERBYSQL+" ")
PRINT @SQL
PRINT @SQLONACCOUNT
PRINT @SQLONACCOUNT1
PRINT @SQLONACCOUNT2
PRINT @SQLONACCOUNT6
PRINT @SQLONACCOUNT3
PRINT @SQLONACCOUNT4
PRINT @SQLONACCOUNT5
PRINT @SQLONACCOUNT7
PRINT ') AS DETAIL '
PRINT @ORDERBYSQL
--SET ANSI_NULLS ON
--SET QUOTED_IDENTIFIER OFF
























GO

/****** Object:  StoredProcedure [dbo].[PROC_OUTSTANDING_ABOVEDAYS]    Script Date: 03/30/2023 12:08:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO


















