name: baalar
description: "Baalar"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.4
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
